# name: Build and Publish Package

# on:
#   push:
#     branches:
#       - main  # Vous pouvez changer la branche cible
#   pull_request:

# jobs:
#   build:
#     name: Build Package
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install build

#     - name: Build distribution files
#       run: |
#         python -m build

#     - name: Upload artifact (optional)
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist-files
#         path: dist/

#   publish:
#     name: Publish Package to PyPI
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install build twine

#     - name: Build distribution files
#       run: |
#         python -m build

#     - name: Publish to PyPI
#       env:
#         TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
#         TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#       run: |
#         twine upload dist/*
